In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [12]:
url = "https://rfm.sapo.pt/top25rfm"
response = requests.get(url)
soup = BeautifulSoup(response.content, "html.parser")

chart_items = soup.find_all("div", class_="top25ItemData")

songs = []

for item in chart_items:
    title = item.select_one("div.tAuthor")
    if title:
        song_title = title.get_text().strip()
        artist = item.select_one("div.tMusic").get_text().strip()
        songs.append({"title": song_title, "artist": artist})
        
for song in songs:
    print(song["title"], "by", song["artist"])

Heaven by Niall Horan
Kiss Me by Dermot Kennedy
Como Tu by Barbara Bandeira feat Ivandro
Flowers by Miley Cyrus
Bloody Mary by Lady Gaga
Casa by DAMA Feat Buba Espinho
Never Gonna Not Dance Again by Pink
Glimpse of Us by Joji
Escola by Os Quatro e Meia
Creepin by Metro Boomin  The Weeknd  21 Savage
I Give Up by Noble
Celestial by Ed Sheeran
A Nossa Dança by Calema
Outros Planos by Rita Rocha
Pilantra by Jão e Anitta
Lay Low by Tiesto
Maria Joana by Nuno Ribeiro, Calema, Mariza
Forget Me by Lewis Capaldi
Despecha by Rosalia
All By Myself by Alok x Sigala vs Ellie Goulding
Made You Look by Meghan Trainor
Agarra Em Mim by Ana Moura
Como Antes by Matias Damasio
Shakira Bzrp Music Sessions Vol 53 by Bzrp X Shakira
La Bachata by Manuel Turizo

In [4]:
df1 = pd.DataFrame(songs)
df1

                                 title                               artist
0                               Heaven                          Niall Horan
1                              Kiss Me                       Dermot Kennedy
2                              Como Tu        Barbara Bandeira feat Ivandro
3                              Flowers                          Miley Cyrus
4                          Bloody Mary                            Lady Gaga
5                                 Casa               DAMA Feat Buba Espinho
6          Never Gonna Not Dance Again                                 Pink
7                        Glimpse of Us                                 Joji
8                               Escola                     Os Quatro e Meia
9                              Creepin  Metro Boomin  The Weeknd  21 Savage
10                           I Give Up                                Noble
11                           Celestial                           Ed Sheeran
12                       A Nossa Dança                               Calema
13                       Outros Planos                           Rita Rocha
14                            Pilantra                         Jão e Anitta
15                             Lay Low                               Tiesto
16                         Maria Joana         Nuno Ribeiro, Calema, Mariza
17                           Forget Me                        Lewis Capaldi
18                            Despecha                              Rosalia
19                       All By Myself      Alok x Sigala vs Ellie Goulding
20                       Made You Look                       Meghan Trainor
21                       Agarra Em Mim                            Ana Moura
22                          Como Antes                       Matias Damasio
23  Shakira Bzrp Music Sessions Vol 53                       Bzrp X Shakira
24                          La Bachata                        Manuel Turizo

In [34]:
url = "https://megahits.sapo.pt/top-10-as-10"
response = requests.get(url)
soup = BeautifulSoup(response.content, "html.parser")

chart_items = soup.find_all("td", class_="pg-gr-li-txtbox2")

songs = []

for item in chart_items:
    title = item.select_one("td.pg-gr-li-np1")
    if title:
        song_title = title.get_text().strip()
        artist = item.select_one("td.pg-gr-li-tx2").get_text().strip()
        songs.append({"title": song_title, "artist": artist})
        
for song in songs:
    print(song["title"], "by", song["artist"])

DIE FOR YOU (REMIX) by THE WEEKND FT. ARIANA GRANDE
HEARTLESS by RICHIE CAMPBEL
ESCAPISM by RAYE FT. 070 SHAKE
COOPED UP by POST MALONE with RODDY RICCH
CONTA-ME by CAROLINA DESLANDES
SNOOZE by SZA
PLANETA by BISPO FT. BÁRBARA TINOCO
KU LO SA by OXLADE x CAMILA CABELLO
SWEETEST PIE by MEGAN THEE STALLION & DUA LIPA
LOVE AGAIN by THE KID LAROI

In [35]:
df2 = pd.DataFrame(songs)
df2

                 title                          artist
0  DIE FOR YOU (REMIX)    THE WEEKND FT. ARIANA GRANDE
1            HEARTLESS                  RICHIE CAMPBEL
2             ESCAPISM              RAYE FT. 070 SHAKE
3            COOPED UP    POST MALONE with RODDY RICCH
4             CONTA-ME              CAROLINA DESLANDES
5               SNOOZE                             SZA
6              PLANETA        BISPO FT. BÁRBARA TINOCO
7             KU LO SA         OXLADE x CAMILA CABELLO
8         SWEETEST PIE  MEGAN THEE STALLION & DUA LIPA
9           LOVE AGAIN                   THE KID LAROI

In [36]:
url = "https://megahits.sapo.pt/top-10-as-10"
response = requests.get(url)
soup = BeautifulSoup(response.content, "html.parser")

chart_items = soup.find_all("div", class_="NZAU7CsuZsMeMQ8zYUu")

songs = []

for item in chart_items:
    title = item.select_one("div.Type__TypeElement-sc-goli3j-0 cvuJgi t_yrXoUO3qGsJS4Y6iXX standalone-ellipsis-one-line")
    if title:
        song_title = title.get_text().strip()
        artist = item.select_one("td.pg-gr-li-tx2").get_text().strip()
        songs.append({"title": song_title, "artist": artist})
        
for song in songs:
    print(song["title"], "by", song["artist"])

In [37]:
df_top = pd.concat([df1, df2])

In [38]:
df_top

                                 title                               artist
0                               Heaven                          Niall Horan
1                              Kiss Me                       Dermot Kennedy
2                              Como Tu        Barbara Bandeira feat Ivandro
3                              Flowers                          Miley Cyrus
4                          Bloody Mary                            Lady Gaga
5                                 Casa               DAMA Feat Buba Espinho
6          Never Gonna Not Dance Again                                 Pink
7                        Glimpse of Us                                 Joji
8                               Escola                     Os Quatro e Meia
9                              Creepin  Metro Boomin  The Weeknd  21 Savage
10                           I Give Up                                Noble
11                           Celestial                           Ed Sheeran
12                       A Nossa Dança                               Calema
13                       Outros Planos                           Rita Rocha
14                            Pilantra                         Jão e Anitta
15                             Lay Low                               Tiesto
16                         Maria Joana         Nuno Ribeiro, Calema, Mariza
17                           Forget Me                        Lewis Capaldi
18                            Despecha                              Rosalia
19                       All By Myself      Alok x Sigala vs Ellie Goulding
20                       Made You Look                       Meghan Trainor
21                       Agarra Em Mim                            Ana Moura
22                          Como Antes                       Matias Damasio
23  Shakira Bzrp Music Sessions Vol 53                       Bzrp X Shakira
24                          La Bachata                        Manuel Turizo
0                  DIE FOR YOU (REMIX)         THE WEEKND FT. ARIANA GRANDE
1                            HEARTLESS                       RICHIE CAMPBEL
2                             ESCAPISM                   RAYE FT. 070 SHAKE
3                            COOPED UP         POST MALONE with RODDY RICCH
4                             CONTA-ME                   CAROLINA DESLANDES
5                               SNOOZE                                  SZA
6                              PLANETA             BISPO FT. BÁRBARA TINOCO
7                             KU LO SA              OXLADE x CAMILA CABELLO
8                         SWEETEST PIE       MEGAN THEE STALLION & DUA LIPA
9                           LOVE AGAIN                        THE KID LAROI

In [39]:
df = pd.read_csv('df.csv')

In [40]:
df

    Unnamed: 0                              title                       artist
0            0                         Last Night                Morgan Wallen
1            1                          Kill Bill                          SZA
2            2                            Flowers                  Miley Cyrus
3            3                    Ella Baila Sola  Eslabon Armado X Peso Pluma
4            4                          Un x100to   Grupo Frontera X Bad Bunny
..         ...                                ...                          ...
95          95                  It Matters To Her              Scotty McCreery
96          96                         Like Crazy                        Jimin
97          97  All Of The Girls You Loved Before                 Taylor Swift
98          98                      5 Leaf Clover                   Luke Combs
99          99                          Big Truck   YoungBoy Never Broke Again

[100 rows x 3 columns]

In [44]:
df = df.drop("Unnamed: 0", axis=1)
df

                                title                       artist
0                          Last Night                Morgan Wallen
1                           Kill Bill                          SZA
2                             Flowers                  Miley Cyrus
3                     Ella Baila Sola  Eslabon Armado X Peso Pluma
4                           Un x100to   Grupo Frontera X Bad Bunny
..                                ...                          ...
95                  It Matters To Her              Scotty McCreery
96                         Like Crazy                        Jimin
97  All Of The Girls You Loved Before                 Taylor Swift
98                      5 Leaf Clover                   Luke Combs
99                          Big Truck   YoungBoy Never Broke Again

[100 rows x 2 columns]

In [46]:
df_top = pd.concat([df_top, df])
df_top

                                title                         artist
0                              Heaven                    Niall Horan
1                             Kiss Me                 Dermot Kennedy
2                             Como Tu  Barbara Bandeira feat Ivandro
3                             Flowers                    Miley Cyrus
4                         Bloody Mary                      Lady Gaga
..                                ...                            ...
95                  It Matters To Her                Scotty McCreery
96                         Like Crazy                          Jimin
97  All Of The Girls You Loved Before                   Taylor Swift
98                      5 Leaf Clover                     Luke Combs
99                          Big Truck     YoungBoy Never Broke Again

[135 rows x 2 columns]

In [48]:
df_top.to_csv('df_top.csv')